### ISSUE TITLE
S3 Bucket Policy

### ISSUE THREAD

**Issue by rdubar** [testdrivenio/django-static-media-files#3]
Thanks for posting this tutorial. Just to let you know, to get s3 to host stattic files with Django, I had to set up my bucket policy as shown below. -- RD

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::BUCKETNAME",
                "arn:aws:s3:::BUCKETNAME/*"
            ]
        }
    ]
}
```

**Comment by mjhea0** [comment]
Thanks for the note, @rdubar. I'm getting ready to refresh the article. I'll take this note into account.
